import { ClockSettings, GradientPreset, CuratedTheme } from '../types';

export const DEFAULT_SETTINGS: ClockSettings = {
  showDate: true,
  showSeconds: true,
  is24Hour: true,
  clockColor: '#ffffff',
  clockFont: 'inter',
  clockWeight: '800',
  showBlinkingSeparator: false,
  bgType: 'gradient',
  bgColor: '#0a0a0c',
  gradientPresetId: 'bold-midnight-radial',
  customGradient: {
    color1: '#1a1a2e',
    color2: '#0a0a0c',
    angle: 135,
  },
  bgOverlayOpacity: 0,
  bgBlur: 0,
  themeMode: 'dark',
  hasCustomImage: false,
  useAtomicSync: true,
  showSyncBadge: true,
  enableBreathingAnimation: true,
  themeId: 'titanium-stealth',
};

export const GRADIENT_PRESETS: GradientPreset[] = [
  {
    id: 'bold-midnight-radial',
    name: 'Bold Midnight (Radial)',
    css: 'radial-gradient(circle at 30% 30%, #1a1a2e 0%, #0a0a0c 100%)',
    textColorHint: '#ffffff',
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    css: 'linear-gradient(135deg, #030712 0%, #0c2340 50%, #031525 100%)',
    textColorHint: '#38bdf8',
  },
  {
    id: 'deep-space',
    name: 'Deep Space',
    css: 'linear-gradient(135deg, #0b0f19 0%, #171d33 45%, #050811 100%)',
    textColorHint: '#ffffff',
  },
  {
    id: 'midnight-neon',
    name: 'Midnight Ocean',
    css: 'linear-gradient(135deg, #021B79 0%, #0575E6 100%)',
    textColorHint: '#ffffff',
  },
  {
    id: 'aurora-borealis',
    name: 'Nordlicht',
    css: 'linear-gradient(135deg, #051923 0%, #003554 35%, #05668d 70%, #02c39a 100%)',
    textColorHint: '#34d399',
  },
  {
    id: 'sunset-glow',
    name: 'Abendrot (Sunset)',
    css: 'linear-gradient(135deg, #2b1055 0%, #754f9a 40%, #ea580c 100%)',
    textColorHint: '#fef08a',
  },
  {
    id: 'cyber-emerald',
    name: 'Smaragd Nacht',
    css: 'linear-gradient(135deg, #022c22 0%, #065f46 50%, #064e3b 100%)',
    textColorHint: '#34d399',
  },
  {
    id: 'obsidian-titanium',
    name: 'Titanium Pure',
    css: 'linear-gradient(135deg, #18181b 0%, #09090b 50%, #1c1917 100%)',
    textColorHint: '#f4f4f5',
  },
  {
    id: 'cosmic-purple',
    name: 'Kosmisches Violett',
    css: 'linear-gradient(135deg, #3b0764 0%, #6b21a8 50%, #1e1b4b 100%)',
    textColorHint: '#faf5ff',
  },
  {
    id: 'golden-hour',
    name: 'Goldene Stunde',
    css: 'linear-gradient(135deg, #1c1917 0%, #78350f 50%, #b45309 100%)',
    textColorHint: '#fef3c7',
  },
  {
    id: 'minimal-light',
    name: 'Heller Schiefer',
    css: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 50%, #cbd5e1 100%)',
    textColorHint: '#0f172a',
  },
];

export const CURATED_THEMES: CuratedTheme[] = [
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    description: 'Tiefes Nachtblau mit kühlem Eisblau-Glühen',
    clockColor: '#38bdf8',
    clockFont: 'inter',
    clockWeight: '800',
    bgType: 'gradient',
    gradientPresetId: 'midnight-blue',
    customGradient: { color1: '#030712', color2: '#0c2340', angle: 135 },
    themeMode: 'dark',
    previewBg: 'linear-gradient(135deg, #030712 0%, #0c2340 50%, #031525 100%)',
    previewTextColor: '#38bdf8',
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Glühender Abendhimmel mit warmem Bernstein-Gold',
    clockColor: '#fef08a',
    clockFont: 'outfit',
    clockWeight: '800',
    bgType: 'gradient',
    gradientPresetId: 'sunset-glow',
    customGradient: { color1: '#2b1055', color2: '#ea580c', angle: 135 },
    themeMode: 'dark',
    previewBg: 'linear-gradient(135deg, #2b1055 0%, #754f9a 40%, #ea580c 100%)',
    previewTextColor: '#fef08a',
  },
  {
    id: 'minimalist-mono',
    name: 'Minimalist Mono',
    description: 'Purer technischer Monospace auf tiefem Obsidian',
    clockColor: '#f4f4f5',
    clockFont: 'mono',
    clockWeight: '400',
    bgType: 'color',
    bgColor: '#09090b',
    themeMode: 'dark',
    previewBg: '#09090b',
    previewTextColor: '#f4f4f5',
  },
  {
    id: 'aurora',
    name: 'Nordlicht (Aurora)',
    description: 'Tiefseegrüner Polarhimmel mit Smaragd-Leuchten',
    clockColor: '#34d399',
    clockFont: 'outfit',
    clockWeight: '800',
    bgType: 'gradient',
    gradientPresetId: 'aurora-borealis',
    customGradient: { color1: '#051923', color2: '#02c39a', angle: 135 },
    themeMode: 'dark',
    previewBg: 'linear-gradient(135deg, #051923 0%, #003554 35%, #02c39a 100%)',
    previewTextColor: '#34d399',
  },
  {
    id: 'cyber-matrix',
    name: 'Cyber Matrix',
    description: 'Elektrisierendes Phosphor-Grün auf Reinschwarz',
    clockColor: '#00ff66',
    clockFont: 'mono',
    clockWeight: '800',
    bgType: 'color',
    bgColor: '#020b05',
    themeMode: 'dark',
    previewBg: 'linear-gradient(180deg, #021a0d 0%, #000000 100%)',
    previewTextColor: '#00ff66',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    description: 'Warme Abendsonne mit tiefem Bernstein & Bronze',
    clockColor: '#f59e0b',
    clockFont: 'inter',
    clockWeight: '800',
    bgType: 'gradient',
    gradientPresetId: 'golden-hour',
    customGradient: { color1: '#1c1917', color2: '#b45309', angle: 135 },
    themeMode: 'dark',
    previewBg: 'linear-gradient(135deg, #1c1917 0%, #78350f 50%, #b45309 100%)',
    previewTextColor: '#f59e0b',
  },
  {
    id: 'cosmic-purple',
    name: 'Cosmic Nebula',
    description: 'Kosmischer Sternennebel mit zartem Flieder',
    clockColor: '#e9d5ff',
    clockFont: 'outfit',
    clockWeight: '800',
    bgType: 'gradient',
    gradientPresetId: 'cosmic-purple',
    customGradient: { color1: '#1e1035', color2: '#6b21a8', angle: 135 },
    themeMode: 'dark',
    previewBg: 'linear-gradient(135deg, #1e1035 0%, #6b21a8 50%, #1e1b4b 100%)',
    previewTextColor: '#e9d5ff',
  },
  {
    id: 'titanium-stealth',
    name: 'Titanium Stealth',
    description: 'Dunkles Graphit-Chassis mit edlem Reinweiß',
    clockColor: '#ffffff',
    clockFont: 'inter',
    clockWeight: '800',
    bgType: 'gradient',
    gradientPresetId: 'bold-midnight-radial',
    customGradient: { color1: '#1a1a2e', color2: '#0a0a0c', angle: 135 },
    themeMode: 'dark',
    previewBg: 'radial-gradient(circle at 30% 30%, #1a1a2e 0%, #0a0a0c 100%)',
    previewTextColor: '#ffffff',
  },
  {
    id: 'clean-paper-light',
    name: 'Clean Studio Light',
    description: 'Klarer heller Schiefer mit tiefblauem Kontrast',
    clockColor: '#0f172a',
    clockFont: 'inter',
    clockWeight: '800',
    bgType: 'gradient',
    gradientPresetId: 'minimal-light',
    customGradient: { color1: '#f8fafc', color2: '#cbd5e1', angle: 135 },
    themeMode: 'light',
    previewBg: 'linear-gradient(135deg, #f8fafc 0%, #cbd5e1 100%)',
    previewTextColor: '#0f172a',
  },
  {
    id: 'digital-retro-red',
    name: 'Digital Retro LED',
    description: 'Klassischer LED-Wecker in leuchtendem Signalrot',
    clockColor: '#ef4444',
    clockFont: 'mono',
    clockWeight: '800',
    bgType: 'color',
    bgColor: '#000000',
    themeMode: 'dark',
    previewBg: '#000000',
    previewTextColor: '#ef4444',
  },
];

export const CLOCK_COLOR_PALETTES = [
  { name: 'Reinweiß', value: '#ffffff' },
  { name: 'Bold Orange', value: '#FF6321' },
  { name: 'Neon-Grün', value: '#00FF00' },
  { name: 'Warm Bernstein', value: '#F27D26' },
  { name: 'Eisblau', value: '#38bdf8' },
  { name: 'Neon-Cyan', value: '#22d3ee' },
  { name: 'Smaragd', value: '#34d399' },
  { name: 'Sonnen-Gelb', value: '#facc15' },
  { name: 'Koralle', value: '#f43f5e' },
  { name: 'Lavendel', value: '#c084fc' },
];

export const BG_COLOR_PALETTES = [
  { name: 'Bold Obsidian', value: '#0a0a0c' },
  { name: 'Tiefes Schwarz', value: '#000000' },
  { name: 'Midnight Navy', value: '#1a1a2e' },
  { name: 'Anthrazit', value: '#121216' },
  { name: 'Dunkles Petrol', value: '#071e22' },
  { name: 'Dunkles Waldgrün', value: '#0b2016' },
  { name: 'Klares Weiß', value: '#f8fafc' },
  { name: 'Sanftes Schiefer', value: '#e2e8f0' },
];
